INFER_YAML:         # if not specified, only training will be excuted
  - photo_infer


OPT:
  lr: 0.0001
  betas: [0.5, 0.999]

NET:
  img_ch: 3
  net_ch: 128

DESC:
  - test-nomodify

TRAIN:
  losses:
    - ssim11
    - mse

  iter_per_scale: 500
  pixel_shuffle_p: 0.005    # 0.005 -> 0.5%

DATASET:
  img_path: /mnt/e/PyCharmProjects/underwater/inputs/SinCycleTests/raw/blur_fish.png

  # img_shape: [120, 80]    # the training image will be resized to (120, 80)

  img_shape: 512            # the training image will be resized,
                            #     and the longer side will be 512px,
                            #     keeping the original aspect ratio
  # ---------------------------------------------------------------------------
